export enum EFrameCommand {
	RENDER_FRAME = 'RENDER_FRAME',
	SWITCH_DRAW_TOOL = 'SWITCH_DRAW_TOOL',
	REFRESH_RTREE = 'REFRESH_RTREE',
	CLEAR_ALL_SELECTS = 'CLEAR_ALL_SELECTS',
	SET_STATIC_REST = 'SET_STATIC_REST',
}

export enum EDrawD2ToolCommand {
	BLANK_DROP = 'BLANK_DROP',
	D2LINE = 'D2LINE',
	D2CIRCLE = 'D2CIRCLE',
	D2POINT = 'D2POINT',
	D2ARC = 'D2ARC',
	D2TEXT = 'D2TEXT',
	D2IMAGE = 'D2IMAGE',
	D2RECT = 'D2RECT',
}
